site:
  name: Harman Khangura
  site: 'https://harmankhangura.com.au'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"